version: '3.8'

services:
  web:
    build: .
    container_name: smart-classroom-app
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: always